version: '3.13'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      default:
        aliases:
          - cassandra
    volumes:
      - cassandra:/var/lib/cassandra

  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      default:
        aliases:
          - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  pagila:
    container_name: pagila
    build:
      context: ./pagila
      dockerfile: Dockerfile
      args:
        PAGILA_REPOSITORY: ${PAGILA_REPOSITORY}
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${PAGILA_USER}
      POSTGRES_PASSWORD: ${PAGILA_PASSWORD}
    networks:
      default:
        aliases:
          - pagila
    volumes:
      - pagila:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: daplayful@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres:postgres

  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'.
      - GRANT_SUDO=yes
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  postgres:
  cassandra:
  pgadmin:
  pagila:
