version: '3.13'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      notebooks:
        aliases:
          - cassandra
    volumes:
      - cassandra:/var/lib/cassandra

  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    networks:
      notebooks:
        aliases:
          - postgres
    expose:
      - 5432

    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: daplayful@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      notebooks:
        aliases:
          - pgadmin
    links:
      - postgres:postgres

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      notebooks:
    volumes:
      - ./notebooks:/home/jovyan/work

networks:
  notebooks:

volumes:
  postgres:
  cassandra:
  pgadmin: