version: '3.13'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      default:
        aliases:
          - cassandra
    volumes:
      - cassandra:/var/lib/cassandra
    profiles:
      - cassandra

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      default:
        aliases:
          - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles:
      - plain_postgres

  pagila:
    container_name: pagila
    build:
      context: ./pagila
      dockerfile: Dockerfile
      args:
        PAGILA_DATA: ${PAGILA_DATA}
    environment:
      PAGILA_DB_NAME: ${PAGILA_DB_NAME}
      POSTGRES_USER: ${PAGILA_USER}
      POSTGRES_PASSWORD: ${PAGILA_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      default:
        aliases:
          - pagila
    command: >
      -c work_mem=4GB
      -c maintenance_work_mem=4GB
      -c max_wal_size=4GB
    volumes:
      - pagila:/var/lib/postgresql/data
    profiles:
      - pagila

  flights_db:
    container_name: flight_postgres
    build:
      context: ./flight_db
      dockerfile: Dockerfile
      args:
        SCRIPT_PATH: ${FLIGHT_SCRIPT_LOCATION}
    environment:
      DB_NAME: ${FLIGHTS_DB_NAME}
      POSTGRES_USER: ${FLIGHTS_USER}
      POSTGRES_PASSWORD: ${FLIGHTS_PASSWORD}
      SQL_SCRIPT_NAME: ${FLIGHT_SCRIPT_NAME}
    networks:
      default:
        aliases:
          - flights_db
    volumes:
      - flights_db:/var/lib/postgresql/data
    profiles:
      - flights_db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: daplayful@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin
    profiles:
      - plain_postgres
      - pagila
      - flights_db

  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'.
      - GRANT_SUDO=yes
    volumes:
      - ./notebooks:/home/jovyan/work
    profiles:
      - jupyter

volumes:
  postgres:
  cassandra:
  pgadmin:
  pagila:
  flights_db:
