version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka_broker_0:
    container_name: kafka_broker_0
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - kafka:/bitnami
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_JMX_PORT=9997
    depends_on:
      - zookeeper

  kafka_ui:
    container_name: kafka_ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka_broker_0:9092

  jupyter:
    container_name: jupyter
    image: jupyter/base-notebook:latest
    ports:
      - "8081:8888"
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'.
      - GRANT_SUDO=yes
    volumes:
      - ./artifacts/notebooks:/home/jovyan/work
    profiles:
      - jupyter

volumes:
  zookeeper:
  kafka:
